
name: Web Automation and API Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:

    runs-on: ubuntu-latest

    steps:
    #download repo
    - uses: actions/checkout@v3

    #setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    #install browser
    - name: Setup Edge
      uses: browser-actions/setup-edge@v1.1.0

    #Setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew 

    #Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber

    #Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.3
      if: always ()
      with:
        name: Cucumber Report 
        path: reports
        
    #Execute gradle command for running API test (add this step)
    - name: Execute API Test
      run: ./gradlew apiTest  # Make sure to replace 'apiTest' with the actual task name for your API tests

    #Archive API Test Result (add this step)
    - name: Archive API Test Result
      uses: actions/upload-artifact@v3.1.3
      if: always()
      with:
        name: API Test Report
        path: build/test-results/apiTest  # Update the path to the actual directory containing API test reports
        

    #Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always ()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PUBLISH_DIR: reports
