
name: Web Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #download repo
    - uses: actions/checkout@v3

    #setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    #install browser
    - name: Setup Edge
      uses: browser-actions/setup-edge@v1.1.0

    #Setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew 

    #Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber

    

